### ISSUE TITLE
compiling 1.4.0 on Linux

### ISSUE THREAD

**Issue by hdatma** [trusteddomainproject/OpenDMARC#100]
```
>curl -qLO https://github.com/trusteddomainproject/OpenDMARC/archive/rel-opendmarc-1-4-0.tar.gz
>tar -zxf rel-opendmarc-1-4-0.tar.gz
>cd OpenDMARC-rel-opendmarc-1-4-0/
>./AutoBuild.sh 
Building opendmarc
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:66: installing 'build-aux/compile'
configure.ac:69: installing 'build-aux/config.guess'
configure.ac:69: installing 'build-aux/config.sub'
configure.ac:45: installing 'build-aux/install-sh'
configure.ac:45: installing 'build-aux/missing'
configure.ac:494: error: required file 'docs/Makefile.in' not found
libopendmarc/Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1
./configure -q --with-wall -C --with-spf
configure: error: need workable resolver library
Fatal ERROR: "./configure -q --with-wall -C --with-spf" failed.
```

**Comment by hdatma** [comment]
Hey developers, do you compile the code before releasing it?

**Comment by amarchandole** [comment]
Hi, faced a similar issue but should be resolved by https://github.com/trusteddomainproject/OpenDMARC/pull/96/commits/035b702eabe46532b708905c8432ca94176bd2e9

**Comment by hdatma** [comment]
The doc patch is also included in https://github.com/trusteddomainproject/OpenDMARC/issues/87

**Comment by hdatma** [comment]
The problem is not the existence of patches. The problem is how to include them in the release. Linux and BSD distributions are not contributing to mainstream (here), and the main developers are not keeping the code up to date.

**Comment by celesteking** [comment]
QA is lacking in this product.

**Comment by thegushi** [comment]
Hey there.  I'm the FreeBSD port maintainer for opendmarc.  I've been in touch with MSK out of band, and it would be way easier if these were made into pull requests.  Could that be done?  If not, I can go in and create my own repo with a corresponding pull request.  Just let me know how to proceed.

**Comment by thegushi** [comment]
Is the resolver issue still present if you apply the doc patch?  If so, which linux distro and version?  Thanks.

**Comment by hdatma** [comment]
> Hey there. I'm the FreeBSD port maintainer for opendmarc. I've been in touch with MSK out of band, and it would be way easier if these were made into pull requests. Could that be done? If not, I can go in and create my own repo with a corresponding pull request. Just let me know how to proceed.

Although we can all create repos with corresponding pull requests, the existence of old requests shows that there is a root problem of a different nature. Read it this way: if you make a repo with all the patches you can find lying around here and elsewhere, then make a pull request, what makes you think they will make it to a release?

If you spend time on a fork of OpenDMARC, with all the patches that work for you and for other people, then you could take over ownership of the project, because the owner(s) are not. I would be happy with it, as we could finally have a release that unifies all efforts, and a production server that works as intended. But is not up to anyone of us to decide ownership of someone else's project.

What we need here is that the project owner(s) spend a Saturday with their ass(es) on the chair, read each pending issue and pull request, add the patches to their source code, and issue a pre-release. Then we can double-check and confirm whether is works. What's the matter with MSK? Why is he holding the helm when he is clearly busy elsewhere? 

Ask MSK to pass on the helm to you, at least for the next release, and let's spend a weekend all together to make the best release ever.

**Comment by thegushi** [comment]
> > Hey there. I'm the FreeBSD port maintainer for opendmarc. I've been in touch with MSK out of band, and it would be way easier if these were made into pull requests. Could that be done? If not, I can go in and create my own repo with a corresponding pull request. Just let me know how to proceed.
> 
> Although we can all create repos with corresponding pull requests, the existence of old requests shows that there is a root problem of a different nature. Read it this way: if you make a repo with all the patches you can find lying around here and elsewhere, then make a pull request, what makes you think they will make it to a release?

I've just dropped about ten of your patches into a merge request, giving you credit for them.  Let's find out if that works -- otherwise, there's my own github that I can base a FreeBSD port on.  I've triaged another five or six issues.  I'm not a software author, I'm a sysadmin and network operator.  I can log compile warnings, wrangle patches and throw them into CI pools, but I'm not the person who's going to write new swaths of code that implement RFCs.

> If you spend time on a fork of OpenDMARC, with all the patches that work for you and for other people, then you could take over ownership of the project, because the owner(s) are not.

There was a release last month.  I'm hoping that it shook things down such that people will actually test things more, and releases can be more frequent.

I know if there's an opendmarc140 port in FreeBSD mainline, it will see much more usage and get more reports in.

> I would be happy with it, as we could finally have a release that unifies all efforts, and a production server that works as intended. But is not up to anyone of us to decide ownership of someone else's project.
> 
> What we need here is that the project owner(s) spend a Saturday with their ass(es) on the chair, read each pending issue and pull request, add the patches to their source code, and issue a pre-release. Then we can double-check and confirm whether is works. What's the matter with MSK? Why is he holding the helm when he is clearly busy elsewhere?

I'm just looking to move the project forward without reducing things to personal attacks.  Life happens to people, especially this year, and being reductionist won't move us forward.
> 
> Ask MSK to pass on the helm to you, at least for the next release, and let's spend a weekend all together to make the best release ever.

I would like to eventually get access to the project, even in a triage role.  I'd like to try and do more active QA.  I have the tools a FreeBSD port maintainer might (port-lint, ports-qa, poudriere testport).  I've got access to enough VM infrastructure to spin up more testing VMs.  

I'd like to with with the owners to move forward and close out the sourceforge pages, and gain a single source of truth.

I'd love to come up with a "how to contribute" document.  I'd like to get more tags added here on github.  

But let's get this 1.4.0 release to a stable build point first, if we can.

**Comment by martinbogo** [comment]
Hey @TheGushi

Please get in contact with me at your earliest convenience.  I'd like to
discuss giving you commit access to The Trusted Domain Project so that you
can continue doing active QA and answer issues here.

Sincerely,
Martin
(martinbogo@gmail.com)

**Comment by thegushi** [comment]
So, that seems to have worked out well. I don't exactly have commit access yet (need to get permission from the day job just in case there's a conflict of interest)￼.

So I can reproduce/qa this, which Linux were you originally compiling this on (distro and version).

**Comment by hdatma** [comment]
Congratulation on joining the maintainers list. Version 1.4.1 is going to make many people happy.

**Comment by thegushi** [comment]
That reminds me -- thanks for the bug reports and patches you're submitting.  How would you like to be credited in the release-notes?  We could just say "hdatma @ github" or "Rupert" or list an email address.  Or just leave the contribs uncredited.  Completely your choice.  We're happy to give credit where it's due.

-Dan

**Comment by thegushi** [comment]
Note that other than asking how you'd like to be credited, this can be closed out.  Feel free to drop me a line privately.  github - gushi - org

**Comment by thegushi** [comment]
I'll close this out with my original suggestion (hdatma at github) after all, that's public here on github anyway.  If you prefer something else, you know how to reach us.

**Comment by martinbogo** [comment]
Twas merged, and so this issue is closed.

**Comment by hdatma** [comment]
> That reminds me -- thanks for the bug reports and patches you're submitting. How would you like to be credited in the release-notes? We could just say "hdatma @ github" or "Rupert" or list an email address. Or just leave the contribs uncredited. Completely your choice. We're happy to give credit where it's due.
> 
> -Dan

Rupert Gallagher (ruga@protonmail.com)
