### ISSUE TITLE
Close SourceForge OpenDMARC pages

### ISSUE THREAD

**Issue by juh** [trusteddomainproject/OpenDMARC#101]
The old OpenDMARC on SourceForge do not indicate that development has moved to Github.
Please close the old SourceForge pages or at least redirect to GitHub.

As a sidenote:
Please migrate all the old issues to from SourceForge to Github - there are a lot of patches worth considering!

**Comment by thegushi** [comment]
Juri,

I've just put in a pull request (#114) that removes references to sourceforge from most of the code (really just the human-readable docs and some spec files).  There's still work to be done involving porting over patches, and we're going to heavily make note of the fact that we're on GitHub now in our next release.

Closing the actual SF site (or perhaps "hiding" it and making it read-only, so we still have access) is a worthwhile thing to do, but you're quite correct that there may be a number of good patches hiding out there.  There may also be a number of already-resolved user questions, so...mixed bag.

That said, if there's anything you've submitted as a patch over there that you think continues to be useful (your name is not unfamiliar to me and the circles I've been moving in for a while), our preferred form of contribution is "pull request".  Github makes it somewhat annoyingly hard to detect that a patch pasted in-line with an issue (which it helpfully colors in and everything) needs to be applied to your code.

Once 114 is merged, we'll close this out, but there's certainly more to do -- but it's got little to do with *the actual code* (if you understand my distinction there).

Best and stay safe,

**Comment by martinbogo** [comment]
#114 has been merged to develop
