### ISSUE TITLE
DNS issues if dmarc policy is using a CNAME

### ISSUE THREAD

**Issue by jbouwh** [trusteddomainproject/OpenDMARC#103]
### Background
When receiving mail from domains that public a direct TXT record the dmarc policy is handled correctly. When the DMARC policy is linked through a CNAME, the result is **unpredictable**. Some times the policy is evaluated correctly, other times there a `none` policy is mentioned indicating a DNS failure.
To prevent timeout issues the time out sessing was set to 10 seconds. Local DNS lookup queries show no issues. No other services indicate there are DNS issues.

### Problem
The evaluation to a none policy could allow mail to be received that should be rejected.

### opendmarc version
$ sudo opendmarc -V
opendmarc: OpenDMARC Filter v1.3.2
        SMFI_VERSION 0x1000001
        libmilter version 1.0.1
        Active code options:
                WITH_SPF
                WITH_SPF2
                
### Distribution
DNS resolver: Local DNS resolver/server on debian 10.8.

### Config
`/etc/opendmarc.conf`
```
# This is a basic configuration that can easily be adapted to suit a standard
# installation. For more advanced options, see openmarc.conf(5) and/or
# /usr/share/doc/opendmarc/examples/opendmarc.conf.sample.

##  AuthservID (string)
##      defaults to MTA name
##
##  Sets the "authserv-id" to use when generating the Authentication-Results:
##  header field after verifying a message.  If the string "HOSTNAME" is
##  provided, the name of the host running the filter (as returned by the
##  gethostname(3) function) will be used.
#
# AuthservID name

##  FailureReports { true | false }
##      default "false"
##
##  Enables generation of failure reports when the DMARC test fails and the
##  purported sender of the message has requested such reports.  Reports are
##  formatted per RFC6591.
#
# FailureReports false

##  PidFile path
##      default (none)
##
##  Specifies the path to a file that should be created at process start
##  containing the process ID.
#
PidFile /var/run/opendmarc/opendmarc.pid

##  PublicSuffixList path
##      default (none)
##
##  Specifies the path to a file that contains top-level domains (TLDs) that
##  will be used to compute the Organizational Domain for a given domain name,
##  as described in the DMARC specification.  If not provided, the filter will
##  not be able to determine the Organizational Domain and only the presented
##  domain will be evaluated.
#
PublicSuffixList /usr/share/publicsuffix

##  RejectFailures { true | false }
##      default "false"
##
##  If set, messages will be rejected if they fail the DMARC evaluation, or
##  temp-failed if evaluation could not be completed.  By default, no message
##  will be rejected or temp-failed regardless of the outcome of the DMARC
##  evaluation of the message.  Instead, an Authentication-Results header
##  field will be added.
#
RejectFailures true

##  Socket socketspec
##      default (none)
##
##  Specifies the socket that should be established by the filter to receive
##  connections from sendmail(8) in order to provide service.  socketspec is
##  in one of two forms: local:path, which creates a UNIX domain socket at
##  the specified path, or inet:port[@host] or inet6:port[@host] which creates
##  a TCP socket on the specified port for the appropriate protocol family.
##  If the host is not given as either a hostname or an IP address, the
##  socket will be listening on all interfaces.  This option is mandatory
##  either in the configuration file or on the command line.  If an IP
##  address is used, it must be enclosed in square brackets.
#
Socket local:/var/run/opendmarc/opendmarc.sock

##  Syslog { true | false }
##      default "false"
##
##  Log via calls to syslog(3) any interesting activity.
#
Syslog true
##  SyslogFacility facility-name
##      default "mail"
##
##  Log via calls to syslog(3) using the named facility.  The facility names
##  are the same as the ones allowed in syslog.conf(5).
#
# SyslogFacility mail

##  TrustedAuthservIDs string
##      default HOSTNAME
##
##  Specifies one or more "authserv-id" values to trust as relaying true
##  upstream DKIM and SPF results.  The default is to use the name of
##  the MTA processing the message.  To specify a list, separate each entry
##  with a comma.  The key word "HOSTNAME" will be replaced by the name of
##  the host running the filter as reported by the gethostname(3) function.
#
# TrustedAuthservIDs HOSTNAME

##  UMask mask
##      default (none)
##
##  Requests a specific permissions mask to be used for file creation.  This
##  only really applies to creation of the socket when Socket specifies a
##  UNIX domain socket, and to the HistoryFile and PidFile (if any); temporary
##  files are normally created by the mkstemp(3) function that enforces a
##  specific file mode on creation regardless of the process umask.  See
##  umask(2) for more information.
#
UMask 0002

##  UserID user[:group]
##      default (none)
##
##  Attempts to become the specified userid before starting operations.
##  The process will be assigned all of the groups and primary group ID of
##  the named userid unless an alternate group is specified.
#
UserID opendmarc:opendmarc
IgnoreHosts /etc/opendmarc/ignore.hosts
IgnoreAuthenticatedClients true
HistoryFile /var/run/opendmarc/opendmarc.dat
SoftwareHeader true
DNSTimeout 10
MilterDebug 1

Socket local:/var/spool/postfix/opendmarc/opendmarc.sock
```

**Comment by jbouwh** [comment]
Logged a ticket at sourceforge.net:
(https://sourceforge.net/p/opendmarc/tickets/241/)

**Comment by martinbogo** [comment]
@jbouwh : We're working as quickly as possible to remove the last vestiges of the SourceForge repository.   We'll be keeping track of the issue here on GitHub but it may take a bit of time to get to this one as we're working on merging many PR's and fixing things up for a 1.4.1 update.

You've done a fantastic job of documenting this, so it will be a lot easier for @mskucherawy, @toddherr, @AntiFreeze, @thegushi and I to address it as part of a 1.5.0 release.   If there's anything else you think of while we're getting there, please update it here in GitHub.

**Comment by celesteking** [comment]
For the devs, you might want to set up dnsmasq and configure it so that it outputs both CNAME and a TXT record for a domain:

```ini
txt-record=_dmarc.mydom.local,"v=DMARC1; p=reject; ruf=mailto:top@x.local;"
cname=_dmarc.mydom.local,bleh.mydom.local
txt-record=bleh.mydom.local,"v=DMARC1; p=reject; ruf=mailto:bleh@x.local;"
```
I don't believe any other dns server would allow you to do that, but worth testing against this atrocity.

**Comment by thegushi** [comment]
When you say "local", do you mean 127.0.0.1 -- or like, local to your network?  If so, which software?  Is it validating?  And is it EDNS0 aware?

I understand you might not want to upload a tcpdump to this github page, but could I ask you to capture a few of the troublesome queries? (Both between opendmarc and your resolver, and between your resolver and the world). My day job is in the DNS, and this might be an implementation issue outside of opendmarc.

**Comment by mskucherawy** [comment]
Is there a live domain for which the _dmarc TXT record is a CNAME?  We can set one up of course, but an existing one saves us that step.

**Comment by jbouwh** [comment]
Try rijksoverheid.nl with s=Selector1

**Comment by thegushi** [comment]
It's believed that this was fixed with a missed if ( type != type) check that was supposed to be if (type != T_TEXT).  If you feel like downloading our develop branch and testing it out we'd love that, or you can wait for that to release and see if the problem still evidences there.

I'm targeting this to the 1.4.1 milestone, but in the event it doesn't show up, we can retarget.  I'm going to mark this with the needs-testing flag, but that's going to be on you.

Feel free to comment here if you feel there's more action on our part required.

**Comment by thegushi** [comment]
We'd like to release this, could you please check out and test?

**Comment by mskucherawy** [comment]
I think what's going on here is that the DNS reply processing code doesn't handle RRTYPEs other than TXT and CNAME well.  Any other type causes a lookup error.  The sample domain name given is signed with DNSSEC, so we also get a RRSIG record, which causes us to fail.  The apparent randomness you're seeing is probably explained by your resolve returning the answers in arbitrary order; if in that ordering the TXT comes before the RRSIG, you get normal operation.

**Comment by thegushi** [comment]
We've applied a fix for this to our "develop" branch (just last evening).  If you're able to check out the develop branch and test we would love to hear from you.

**Comment by thegushi** [comment]
We believe this has been fixed and I'm closing it out.  When 1.4.1 drops if this issue persists, please feel free to reopen this issue.

**Comment by jbouwh** [comment]
Thnx for fixing. After discussing this internally, in our opnion, this issue should be considered as a security vulnerability. Since we know that quite some organisations use CNAME for refering to DMARC policies, therefore we believe it is crucial that current users get notified and are able to patch their environments.
P.S. We would like to see current distributions patched to resolve this bug asap.
