### ISSUE TITLE
unable to parse From header field

### ISSUE THREAD

**Issue by celesteking** [trusteddomainproject/OpenDMARC#104]
Hi. Getting this error on RFC compliant from field: 
`From: "'X, Y' via Z" <spam@googlegroups.com>`

    opendmarc[1288282]: 5B88D607F: unable to parse From header field

    opendmarc: OpenDMARC Filter v1.4.0
            SMFI_VERSION 0x1000001
            libmilter version 1.0.1
            Active code options:
                    WITH_SPF

This project is riddled with bugs.

**Comment by celesteking** [comment]
also see #72

**Comment by mskucherawy** [comment]
Yep, that's a bug.  Fixed with the above commit.
