### ISSUE TITLE
Reopen: pass failed messages from p=quarantine domains

### ISSUE THREAD

**Issue by weishen** [trusteddomainproject/OpenDMARC#105]
The original issue is [https://sourceforge.net/p/opendmarc/tickets/138/](url).  I'd like to repost it here for convenience.

> Problem: messages from domains announcing p=quarantaine that fail the DMARC check
stay in the MTA queue until administrative interventions.
>Marcos Moraes suggested a patch to let such messages pass even if "rejectfailures: yes"
That enables the administrator to configure later A-R handling
see http://www.trusteddomain.org/pipermail/opendmarc-dev/2015-July/000239.html
>There where a suggestion from Scott K regarding the name of the config option.
Somehow I'm also not very comfortable with the name, but I've no better suggestion..
>Marco named it "HoldQuarantinedMessages" with default "false"
That do not require an administrator to all any additional configuration because the default
is exaclty what an admin may want: "not hold Messages the otherwise would be quarantined"
>Andreas

The config option like "HoldQuarantinedMessages" is very useful,  please add it.

**Comment by glts** [comment]
See also #77.

**Comment by thegushi** [comment]
Hey there. 

I'm working with the Trusted Domain Project to triage some old tickets, but don't have full admin access here yet.  (Layer9, grumble grumble).

 I found this (fairly trivial) patch from a few years back, and it looks pretty nondisruptive easy to add.  It also looks like there's no easy option in postfix to override the behavior as dictated by a milter.  (I don't know about sendmail) so I'm going to go ahead and prepare a pull request for this from my own GH repo.  The patch is slightly incomplete (it's missing example documentation for the fully documented config.sample) so I'll need to write that up as well.

**Comment by thegushi** [comment]
Pull request in place to resolve this (which I just saw has been merged to the develop branch).  See #77 for this.  (This one can be merged/closed as duplicate)

**Comment by martinbogo** [comment]
Merged, closed.
