### ISSUE TITLE
Credit where it's due: missing line in RELEASE_NOTES

### ISSUE THREAD

**Issue by thegushi** [trusteddomainproject/OpenDMARC#107]
Line 23 of current RELEASE_NOTES:

Fix Authentication-Results tokenizing.  Patch from 

Feels like a texteditor chopped a line.

**Comment by bicknell** [comment]
Could it be this pull request: https://github.com/trusteddomainproject/OpenDMARC/pull/46

**Comment by thegushi** [comment]
Leo: I think it is.  Waiting on the fellow to comment there before pushing a commit.  If he doesn't answer in a day or three we'll just use his github username.

**Comment by thegushi** [comment]
He's commented and I've amended the release notes in the develop branch.
