### ISSUE TITLE
dmarcf_mail_parse_multi is missing a prototype.

### ISSUE THREAD

**Issue by bicknell** [trusteddomainproject/OpenDMARC#120]
The compiler reports:

```
opendmarc.c:2390:11: warning: implicit declaration of function 'dmarcf_mail_parse_multi' is invalid in C99 [-Wimplicit-function-declaration]
        status = dmarcf_mail_parse_multi(addrbuf, &users, &domains);
```

https://github.com/trusteddomainproject/OpenDMARC/pull/119 adds the prototype.

**Comment by hdatma** [comment]
I do not see this warning on OpenBSD.

**Comment by bicknell** [comment]
Found in FreeBSD 12.2 which uses an LLVM compiler.  Note the warning is about compliance with the C99 standard.   GNU C, which I believe is the default on OpenBSD, defaults to "gnu90", a proprietary GNU standard.  This may not be a default warning in that standard.  I suspect adding -Wall to CFLAGS before compiling would make it appear on OpenBSD, but I don't have an OpenBSD machine to test.

**Comment by thegushi** [comment]
Merged.  Thanks for your commit.  How would you like to be credited?

**Comment by bicknell** [comment]
I do not require any credit.
