### ISSUE TITLE
string traverser

### ISSUE THREAD

**Issue by celesteking** [trusteddomainproject/OpenDMARC#136]
```c
dmarcf_mail_parse_multi(unsigned char *line, unsigned char ***users_out,
                        unsigned char ***domains_out)
{
	for (p = line; !done; p++)
	{
		switch (*p)
		{
		  case '\0':
			if (parens != 0 || quoted)
				continue;
```

You should never try to advance null-terminated string pointer once you've encountered null. This is a big mistake and should be fixed. 

(Although strangely, I wasn't able to crash protonmail, which allegedly is using opendmarc.)

**Comment by mskucherawy** [comment]
Yep, good catch.
