### ISSUE TITLE
Passing incomparable pointer type to DNS functions.

### ISSUE THREAD

**Issue by bicknell** [trusteddomainproject/OpenDMARC#148]
On the develop branch with CentOS 8.3, gcc version xxx reports:

```
opendmarc_dns.c: In function ‘dmarc_dns_get_record’:
opendmarc_dns.c:210:50: warning: passing argument 2 of ‘opendmarc_policy_library_dns_hook’ from incompatible pointer type [-Wincompatible-pointer-types]
                                                  &resp.nsaddr_list);
                                                  ^~~~~~~~~~~~~~~~~
In file included from opendmarc_dns.c:15:
opendmarc_internal.h:243:75: note: expected ‘struct sockaddr_in *’ but argument is of type ‘struct sockaddr_in (*)[3]’
 void opendmarc_policy_library_dns_hook(int *nscountp, struct sockaddr_in *nsaddr_list);
                                                       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```

I'm not quite sure what the logic fix is here.  It looks like the called function expects a single sockaddr_in, but it looks like the calling function has an array of them, 3 deep in this case.

**Comment by mskucherawy** [comment]
But last I checked it's legal in C to refer to an array via a pointer to (usually) its first element.  I guess the call could be to use `&resp.nsaddr_list[0]`:

```
int main()
{
        int x[2];

        printf("%p %p\n", x, &x[0]);
}
```
...when executed yields:
```
0x7fffffffe590 0x7fffffffe590
```

**Comment by bicknell** [comment]
I guess the only question I would ask is, if there are multiple responses in the list is using the first one always the correct behavior?

It's unclear to me what logic the code should follow if there are multiple entries.
