### ISSUE TITLE
Error checking omission in opendmarc_tld.c

### ISSUE THREAD

**Issue by bicknell** [trusteddomainproject/OpenDMARC#149]
On the develop branch...

In function `opendmarc_tld_read_file` the a pointer is declared:

```
        void *  vp;
```

It is then used to capture the return value of a call to `opendmarc_hash_lookup`:

```
                vp = opendmarc_hash_lookup(hashp, revbuf, (void *)revbuf, strlen(revbuf));
```

The information block for that function says:

```
**	Returns:
**		Address of data on success (search or update)
**		NULL and sets non-zero errno on error
```

However vp is never checked for used again in that function.

Either:

1. No error checking is necessary here for some reason, and the variable vp should be removed entirely.
1. Error checking is required here and missing, the value of `vp` should be checked to see if it is NULL and if so some appropriate error behavior handled.

**Comment by mskucherawy** [comment]
This appears to be doing a hash table insert.  We don't care about the returned value,
