### ISSUE TITLE
Can't configure from git clone

### ISSUE THREAD

**Issue by Swallowtail23** [trusteddomainproject/OpenDMARC#155]
I've git cloned and tried all combinations of trying to get this to configure for a make... 
But I think something is missing.

configure.ac:514: error: required file 'docs/Makefile.in' not found

**Comment by thegushi** [comment]
You are probably still on the "Master" branch which has a bug ni the configure.ac.  Do a "git checkout develop" followed by an autoreconf -v -i -f and a ./configure (with whatever args you'd like) and make.

**Comment by thegushi** [comment]
If you hit more issues, feel free to reopen, but this isn't an issue with the code, per se.  (Maybe we should put this in our README.md which Github displays by default on our main site)

**Comment by Swallowtail23** [comment]
I'll try the Develop code.
The key point is there is no documented way to build the code in *any* of the documentation. That also applies to downloading the 1.4.0 tar.gz - that also fails to build with the same error.

If checking out the develop code etc. is the way to build, then yes that should be noted in the README.
