### ISSUE TITLE
Configure run with --with-wall fails on machines without gcc.

### ISSUE THREAD

**Issue by bicknell** [trusteddomainproject/OpenDMARC#157]
FreeBSD 12.1 trying to build the develop branch:

Relevant lines from the run of ./confgure:
```
[some items removed]
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... no
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
[some items removed]
checking for miltertest... yes
checking whether the resolver works without -lresolv... no
checking whether the resolver works with -lresolv... no
configure: error: need workable resolver library
```

Looking in config.log I see it's trying to use gcc, which does not exist on FreeBSD by default:

```
configure:15901: checking whether the resolver works without -lresolv
configure:15910: gcc -Wall -o conftest -g -O2   conftest.c -lrt  >&5
eval: gcc: not found
configure:15910: $? = 127
configure: failed program was:
```

Looking for why, in `configure.ac` I found:

```
AC_ARG_WITH([wall],
        AS_HELP_STRING([--with-wall], [(no default)]),
        CC="gcc -Wall",)
```

I think the right answer is:

```
diff --git a/configure.ac b/configure.ac
index f9df922..b41eadf 100644
--- a/configure.ac
+++ b/configure.ac
@@ -264,7 +264,7 @@ AC_SUBST(ac_aux_dir)
 
 AC_ARG_WITH([wall],
        AS_HELP_STRING([--with-wall], [(no default)]),
-       CC="gcc -Wall",)
+       CFLAGS="$CFLAGS -Wall",)
 
 
 #
```

At least, that worked for me and seemed to do the right thing.

**Comment by bicknell** [comment]
A few additional thoughts.  No right or wrong answer here, just some additional options for the maintainers.

Technically, this is not required.  The builder can achieve the same effect by doing:

```
export CFLAGS="-Wall"
./configure
make
```

Thus the first alternative is to just remove the "--with-wall" option entirely.  It's not strictly needed.  In particularly I've recently been building with `CFLAGS="-Wall -Wno-pointer-sign"` because of the char/unsigned char issue to get all the warnings but that one.

The other alternative is to just add "-Wall" to all builds.  I know several projects that run that way wanting to see code clean against -Wall before accepting.  The biggest impediment to this in the short term is the char/unsigned char thing, until that's fixed making -Wall the default would be.....verbose.  

Finally, for testing purposes and checking if the code is as robust as possible you may want to consider more than -Wall:
* -Wextra works on gcc to enable extra warnings.  I believe clang ignores it.
* -pedantic warns on language extensions.
* -std=xxx sets the C standard you want to target, which also allows you to verify it's clean with older versions if that's a project goal.
* -Werror turns all warnings into hard errors to enforce that no warnings are allowed.
* gcc in particular will not omit some warnings without -O enabled, or -g enabled.  I recommend `-O3 -g` on all diagnostic builds.

**Comment by mskucherawy** [comment]
I just removed it.  It seems strange to me to talk to the compiler and preprocessor directly through dedicated autoconf things when it already offers the CFLAGS hook.  I could see including flags to do so when a particular constellation of flags can get quite lengthy (e.g., what "--disable-shared" does), but that's also what scripts are for.
