### ISSUE TITLE
1.4.1 SPF disagreement

### ISSUE THREAD

**Issue by Swallowtail23** [trusteddomainproject/OpenDMARC#161]
AR headers (top one is pypolicyd-spf, second/third lines are OpenDMARC 1.4.1)

```
Authentication-Results: mail.simonandkate.net; spf=pass (mailfrom) smtp.mailfrom=groups.io (client-ip=66.175.222.108; helo=mail02.groups.io; envelope-from=***@groups.io; receiver=***@***.net)
Authentication-Results: mail.simonandkate.net; dmarc=none (p=none dis=none) header.from=groups.io
Authentication-Results: mail.simonandkate.net; spf=fail smtp.mailfrom=***@groups.io
```

Manual result of SPF assessment (https://www.kitterman.com/spf/test5.py)

```
Mail sent from this IP address: 66.175.222.108
Mail from (Sender): ***@groups.io
Mail checked using this SPF policy: v=spf1 ip4:66.175.222.12 ip4:66.175.222.108 include:mail.zendesk.com include:smtp.zendesk.com ~all
Results - PASS sender SPF authorized

Mail sent from this IP address: 66.175.222.108
Mail Server HELO/EHLO identity: mail02.groups.io

HELO/EHLO Results - none
```

As far as I can see this *should* pass, but OpenDMARC SPF test fails it on MAILFROM.

**Comment by thegushi** [comment]
Yes, there’s further work we’re doing to make mailfrom= look at either a domain or ***@***.***, and look at quoting.  This is a known thing and should be fixed before 1.4.1 releases.

**Comment by thegushi** [comment]
Also, I *JUST NOW* connected your github username with the person I’ve been emailing with on the postfix mailing list, then privately.  (*lightbulb*)

-Dan

**Comment by Swallowtail23** [comment]
Apologies Dan, I should have commented to that effect. 
I'll keep monitoring the develop branch and will test as change are released. I have installed it alongside 1.3.2 on my server, and have defined another service in parallel, so can easily switch between 1.3.2 and the develop branch.

**Comment by mskucherawy** [comment]
Is this still happening on "develop"?  I just pushed some changes that affect SPF evaluation.

**Comment by Swallowtail23** [comment]
I'll recompile, switch back to 1.4.1dev and have a look.

**Comment by Swallowtail23** [comment]
Well the first one that came through looks promising :)

```
Authentication-Results: mail.simonandkate.net; spf=pass (mailfrom) smtp.mailfrom=vip.kogan.com (client-ip=12.130.153.158; helo=omp.vip.kogan.com; envelope-from=store-news@vip.kogan.com; receiver=simon@simonandkate.net)
Authentication-Results: mail.simonandkate.net; dmarc=pass (p=reject dis=none) header.from=vip.kogan.com
**Authentication-Results: mail.simonandkate.net; spf=pass smtp.mailfrom=vip.kogan.com**
```

Good to see the RFC8601-compliant Authentication-Results header too (no local part) (y)

I'll keep checking for any inconsistent evaluations.

**Comment by Swallowtail23** [comment]
I've got a conflict:

```
Authentication-Results: mail.simonandkate.net; spf=pass (mailfrom) smtp.mailfrom=mail45.atl231.mcsv.net (client-ip=198.2.141.45; helo=mail45.atl231.mcsv.net; envelope-from=bounce-mc.us6_14367223.131135-703548c136@mail45.atl231.mcsv.net; receiver=simon@simonandkate.net)
Authentication-Results: mail.simonandkate.net; dmarc=none (p=none dis=none) header.from=brisbanepowerhouse.org
Authentication-Results: mail.simonandkate.net; spf=fail smtp.mailfrom=mail45.atl231.mcsv.net
```

First header is pypolicyd-spf, second and third headers are from OpenDMARC 1.4.1 develop, just built an hour or two ago.

**Comment by Swallowtail23** [comment]
This is the same mailing list which triggered my original message above... just got another email to it, and still a conflict on SPF pass/fail.

```
Authentication-Results: mail.simonandkate.net; spf=pass (mailfrom) smtp.mailfrom=groups.io (client-ip=66.175.222.108; helo=mail02.groups.io; envelope-from=bounce+6376+188929+925173+2363489@groups.io; receiver=simon@simonandkate.net)
Authentication-Results: mail.simonandkate.net; dmarc=fail (p=none dis=none) header.from=hotmail.com
Authentication-Results: mail.simonandkate.net; spf=fail smtp.mailfrom=groups.io
```

**Comment by Swallowtail23** [comment]
I found a message from the same sender to the same mailing list processed on OpenDMARC 1.3.2.

1.3.2:
```
Authentication-Results: mail.simonandkate.net; spf=pass (mailfrom) smtp.mailfrom=groups.io (client-ip=66.175.222.108; helo=mail02.groups.io; envelope-from=bounce+6376+188883+925173+2363489@groups.io; receiver=simon@simonandkate.net)
Authentication-Results: mail.simonandkate.net; dmarc=fail (p=none dis=none) header.from=hotmail.com
Authentication-Results: mail.simonandkate.net; spf=pass smtp.mailfrom=bounce+6376+188883+925173+2363489@groups.io
```

1.4.1 dev:
```
Authentication-Results: mail.simonandkate.net; spf=pass (mailfrom) smtp.mailfrom=groups.io (client-ip=66.175.222.108; helo=mail02.groups.io; envelope-from=bounce+6376+188929+925173+2363489@groups.io; receiver=simon@simonandkate.net)
Authentication-Results: mail.simonandkate.net; dmarc=fail (p=none dis=none) header.from=hotmail.com
Authentication-Results: mail.simonandkate.net; spf=fail smtp.mailfrom=groups.io
```

Different outcome... something has broken.

**Comment by thegushi** [comment]
On Mon, 12 Apr 2021, Swallowtail23 wrote:

> 
> I found a message from the same sender to the same mailing list processed on OpenDMARC 1.3.2.
> 
> 1.3.2:
> 
> Authentication-Results: mail.simonandkate.net; spf=pass (mailfrom) smtp.mailfrom=groups.io (client-ip=66.175.222.108; helo=mail02.groups.io; ***@***.***; 
> ***@***.***)
> Authentication-Results: mail.simonandkate.net; dmarc=fail (p=none dis=none) header.from=hotmail.com
> Authentication-Results: mail.simonandkate.net; spf=pass ***@***.***
> 
> 1.4.1 dev:
> 
> Authentication-Results: mail.simonandkate.net; spf=pass (mailfrom) smtp.mailfrom=groups.io (client-ip=66.175.222.108; helo=mail02.groups.io; ***@***.***; 
> ***@***.***)
> Authentication-Results: mail.simonandkate.net; dmarc=fail (p=none dis=none) header.from=hotmail.com
> Authentication-Results: mail.simonandkate.net; spf=fail smtp.mailfrom=groups.io
> 
> Different outcome... something has broken.

So 1.4.0 would have behaved similarly to 1.3.2 here, I think...

Can you email (privately)  me your full opendmarc config that you're using 
(and are you using libspf2, or the inbuilt spf?)

-Dan

> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.[AAIWKKH7KE2MS32URS7YPEDTIKW2FA5CNFSM42QMDDLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGC54OFQ.gif]
> 
> 
>

-- 

"Little tramp sits in her room all day, sewing dolls!  Children
misbehaving in the basement, and one in the walls, doing his business God
knows where!  You children will be the death of me, *sniff*."

'Mommy', The People Under The Stairs


--------Dan Mahoney--------
Techie,  Sysadmin,  WebGeek
Gushi on efnet/undernet IRC
FB:  fb.com/DanielMahoneyIV
LI:   linkedin.com/in/gushi
Site:  http://www.gushi.org
---------------------------

**Comment by Swallowtail23** [comment]
Inbuilt SPF ("--with-spf"). I'll send config. 
That gets me thinking - I wonder if the EPEL package of 1.3.2 is using libspf2... The end result should be the same either way, but it may be that the difference is internal vs libspf2 rather than a change between versions.
Is there a way to tell which OpenDMARC is using?

**Comment by thegushi** [comment]
Sent from my iPad

> On Apr 12, 2021, at 15:50, Swallowtail23 ***@***.***> wrote:
> 
> ﻿
> Inbuilt SPF ("--with-spf"). I'll send config.
> That gets me thinking - I wonder if the EPEL package of 1.3.2 is using libspf2... The end result should be the same either way, but it may be that the difference is internal vs libspf2 rather than a change between versions.
> Is there a way to tell which OpenDMARC is using?
> 
ldd

**Comment by Swallowtail23** [comment]
OK, yes that is illuminating.

```
[root@emp87 ~]# ldd /usr/sbin/opendmarc    <--1.3.2, EPEL package
        linux-vdso.so.1 (0x00007ffd56ff2000)
        libopendmarc.so.2 => /lib64/libopendmarc.so.2 (0x00007f9b5bad8000)
        libmilter.so.1.0 => /lib64/libmilter.so.1.0 (0x00007f9b5b8c7000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f9b5b6b0000)
        libspf2.so.2 => /lib64/libspf2.so.2 (0x00007f9b5b494000)
        libbsd.so.0 => /lib64/libbsd.so.0 (0x00007f9b5b27b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f9b5b073000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9b5ae53000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9b5aa90000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9b5befb000)
[root@emp87 ~]# ldd /usr/local/sbin/opendmarc   <--1.4.1 compiled and built from develop using built-in SPF
        linux-vdso.so.1 (0x00007ffc247ee000)
        libopendmarc.so.2 => /usr/local/lib/libopendmarc.so.2 (0x00007fb7f4bf5000)
        libmilter.so.1.0 => /lib64/libmilter.so.1.0 (0x00007fb7f49e4000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb7f47c4000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fb7f45ad000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb7f422b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fb7f4023000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb7f3c60000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb7f4e09000)
```

The EPEL package looks like it is built to use libspf2 - that would explain the different outcome. Although it does not help you guys other than confirm that the built-in SPF is not reliable.

**Comment by Swallowtail23** [comment]
I've built 1.4.1 develop against libspf2, and will keep monitoring (no conflicts so far in a couple of hours of emails). 

You guys are aware of the issues with inbuilt SPF checks within OpenDMARC and have already indicated that it will be removed in future versions, so this issue can probably be closed? Looks to me like removing internal SPF checking needs to be brought forward if it fails to accurately assess SPF as often as it appears to.

**Comment by mskucherawy** [comment]
The problem appears to be that we convert the client IP address to an integer using inet_addr() and then pass it through htonl() ostensibly to convert it to network byte order for comparisons.  However, inet_addr() returns it in network byte order already, so this essentially corrupted the integer and then did a test against it which will usually fail.

The code has been that way since the library was first written some seven years ago, so I don't know how it was working in 1.3.2.

The commit above fixes that problem.  I am uncertain whether this is an improvement overall, but this was definitely a bug.  It certainly affected the "ip4" SPF mechanism, and probably "a" as well.
