### ISSUE TITLE
New parameter ‘HoldQuarantinedMessages’ broken

### ISSUE THREAD

**Issue by glts** [trusteddomainproject/OpenDMARC#162]
There are two problems with the recently added configuration parameter `HoldQuarantinedMessages` (3f1530782353ca61b6c6faf00bdd40e487b0de31):

1. It does not work as intended: as it is, the setting applies to policy `reject` instead of policy `quarantine`. (It looks like the original patch was applied to the wrong case statement.)

2. As noted by @celesteking in comment https://github.com/trusteddomainproject/OpenDMARC/issues/77#issuecomment-801441021, you are changing the default behaviour:
previously, policy `quarantine` resulted in the message being quarantined/put on hold when `RejectFailures` is set.
now, policy `quarantine` does no longer result in the message being quarantined when `RejectFailures` is set.
It would be better to keep the default behaviour unchanged.

**Comment by glts** [comment]
To be clear, this should be fixed before the next release. (`p=reject` is now accepted instead of rejected.)

**Comment by mskucherawy** [comment]
The faulty commit went to "master".  It is correct on "develop".  We'll fix this in the release merge.

**Comment by mskucherawy** [comment]
This has been removed from "master", and now the good version from "develop" has been merged to master as part of the 1.4.1 release.
