### ISSUE TITLE
SPF macros not supported?

### ISSUE THREAD

**Issue by Bill-ColeUS** [trusteddomainproject/OpenDMARC#176]
Hello,

When I receive emails from elq.mongodb.com, they always fail SPF checks by opendmarc:

```
SPF(mailfrom): elq.mongodb.com fail
mongodb.com pass
```

Looking at their SPF record, I see they use macros:

```
elq.mongodb.com.	6601	IN	TXT	"v=spf1 include:elq.mongodb.com._nspf.vali.email include:%{i}._ip.%{h}._ehlo.%{d}._spf.vali.email ~all"
```

Spamassassin correctly marks those emails with SPF_PASS. Maybe opendmarc does not support SPF macros?

Thank you.

PS:
I am using opendmarc 1.4.1

**Comment by glts** [comment]
How did you compile OpenDMARC, with libspf2 or the builtin SPF implementation? Do try with libspf2

**Comment by Bill-ColeUS** [comment]
I did not compile it myself, I use the EPEL package.

**Comment by glts** [comment]
Both libspf2 and the built-in SPF implementation support macros.

If the EPEL package uses the built-in implementation, then what you are seeing might have to do with `include` directives not being supported properly. Generally, I would discourage using the built-in SPF implementation. There are serious issues with it, see eg the proposed revision in #170. Either compile with libspf2 or, better still, use an up-to-date third-party SPF component.

**Comment by glts** [comment]
And let me point out that `fail` is an unreasonable SPF result for whichever implementation the EPEL package uses, because the SPF record you show doesn’t have a `fail` qualifier at all!

**Comment by Bill-ColeUS** [comment]
Maybe you could get in touch with the maintainer of the EPEL packages and get them to update their SPF implementation?

Sorry I can't be of much help.
