### ISSUE TITLE
OpenDMARC report says that something failed.

### ISSUE THREAD

**Issue by amiga600** [trusteddomainproject/OpenDMARC#181]
Hi guys.

Here is my DMARC report generated by OpenDMARC:
```
<?xml version="1.0" encoding="UTF-8" ?>
<feedback>
    <report_metadata>
        <org_name>ORG</org_name>
         <email>SENDER</email>
         <report_id>SOURCE:1623773275</report_id>
         <date_range>
         <begin>1623686875</begin>
         <end>1623773275</end>
         </date_range>
    </report_metadata>
    <policy_published>
        <domain>SOURCE</domain>
        <adkim>s</adkim>
        <aspf>s</aspf>
        <p>reject</p>
        <sp>none</sp>
        <pct>100</pct>
    </policy_published>
    <record>
        <row>
            <source_ip>IP</source_ip>
            <count>1</count>
            <policy_evaluated>
                <disposition>none</disposition>
                <dkim>pass</dkim>
                <spf>pass</spf>
                <reason>
                    <type>local_policy</type>
                    <comment>arc=fail</comment>
                </reason>
            </policy_evaluated>
        </row>
        <identifiers>
            <header_from>SOURCE</header_from>
        </identifiers>
        <auth_results>
            <spf>
                <domain>SOURCE</domain>
                <result>pass</result>
            </spf>
            <dkim>
                <domain>SOURCE</domain>
                <selector>default</selector>
                <result>pass</result>
            </dkim>
        </auth_results>
    </record>
</feedback>


```
**arc=fail** - What is this?

**Comment by amiga600** [comment]
And with [Postsrsd](https://github.com/roehling/postsrsd) enabled it is much worse:

```
<?xml version="1.0" encoding="UTF-8" ?>
<feedback>
    <report_metadata>
        <org_name>ORG</org_name>
         <email>SENDER</email>
         <report_id>SOURCE:1623775147</report_id>
         <date_range>
         <begin>1623688747</begin>
         <end>1623775147</end>
         </date_range>
    </report_metadata>
    <policy_published>
        <domain>SOURCE</domain>
        <adkim>s</adkim>
        <aspf>s</aspf>
        <p>reject</p>
        <sp>none</sp>
        <pct>100</pct>
    </policy_published>
    <record>
        <row>
            <source_ip>IP</source_ip>
            <count>1</count>
            <policy_evaluated>
                <disposition>none</disposition>
                <dkim>pass</dkim>
                <spf>fail</spf>
                <reason>
                    <type>local_policy</type>
                    <comment>arc=fail</comment>
                </reason>
            </policy_evaluated>
        </row>
        <identifiers>
            <header_from>SOURCE</header_from>
        </identifiers>
        <auth_results>
            <spf>
                <domain>SRS_DOMAIN</domain>
                <result>pass</result>
            </spf>
            <dkim>
                <domain>SOURCE</domain>
                <selector>default</selector>
                <result>pass</result>
            </dkim>
        </auth_results>
    </record>
</feedback>

```
SPF fail, arc fail... But message was delivered without problem:
```

Authentication-Results: SERVER;
        dkim=pass (2048-bit key; unprotected) header.d=SOURCE header.i=@SOURCE header.a=rsa-sha256 header.s=default header.b=oGW+oinS
X-Spam-Status: No, score=0.138 tagged_above=-999 required=5
        tests=[DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1,
        HEADER_FROM_DIFFERENT_DOMAINS=0.25, L_DMARC_PASS=-0.01,
        SPF_HELO_PASS=-0.001, SPF_PASS=-0.001] autolearn=disabled
DMARC-Filter: OpenDMARC Filter v1.4.1 SERVER 5C5A822389
Authentication-Results: SERVER; dmarc=pass (p=reject dis=none) header.from=SOURCE
Authentication-Results: SERVER; spf=pass smtp.mailfrom=SRS_DOMAIN

```

**Comment by raforg** [comment]
Hi, I'm not an OpenDMARC developer, just passing by. But I'm guessing that arc=fail should mean that there
was an Authenticated Received Chain (ARC) (rfc8617) failure. However, I think that's supposed to be handled
by OpenARC, not OpenDMARC. I think OpenDMARC should defer to OpenARC if ARC headers are present,
but I have no idea how they all fit together, or what happens when you don't have OpenARC.

I wonder if this has anything to do with why I get DMARC failures from the occasional mail server, even though
DKIM passes, for mails to mailing lists that get sent to a gmail account which then forwards it to another email
address. Gmail adds ARC headers. There's nothing wrong with the ARC headers, but maybe their presence
upsets OpenDMARC in the absence of OpenARC. But that doesn't make sense if DKIM or SPF still pass.
It's just wild speculation.

Anyway, if you have access to the headers, look for ARC-Authentication-Results, ARC-Message-Signature, and
ARC-Seal headers. If they are present, then it might have something to do with them. But I don't know what
good knowing that will do.

**Comment by amiga600** [comment]
> 
> 
> Hi, I'm not an OpenDMARC developer, just passing by. But I'm guessing that arc=fail should mean that there
> was an Authenticated Received Chain (ARC) (rfc8617) failure. However, I think that's supposed to be handled
> by OpenARC, not OpenDMARC. I think OpenDMARC should defer to OpenARC if ARC headers are present,
> but I have no idea how they all fit together, or what happens when you don't have OpenARC.
> 
> I wonder if this has anything to do with why I get DMARC failures from the occasional mail server, even though
> DKIM passes, for mails to mailing lists that get sent to a gmail account which then forwards it to another email
> address. Gmail adds ARC headers. There's nothing wrong with the ARC headers, but maybe their presence
> upsets OpenDMARC in the absence of OpenARC. But that doesn't make sense if DKIM or SPF still pass.
> It's just wild speculation.
> 
> Anyway, if you have access to the headers, look for ARC-Authentication-Results, ARC-Message-Signature, and
> ARC-Seal headers. If they are present, then it might have something to do with them. But I don't know what
> good knowing that will do.

Thank you for your reply anyway. :)
