### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dilyanpalauzov** [trusteddomainproject/OpenDMARC#21]
```
  CC       opendmarc-opendmarc.o
  CC       opendmarc-opendmarc-ar.o
  CC       opendmarc-opendmarc-arcares.o
opendmarc-arcares.c: In function ‘opendmarc_arcares_parse’:
opendmarc-arcares.c:261:5: warning: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Wimplicit-function-decla
ration]
     strlcpy(aar->authserv_id, tag_value, sizeof aar->authserv_id);
     ^~~~~~~
     strncpy
opendmarc-arcares.c: In function ‘opendmarc_arcares_arc_parse’:
opendmarc-arcares.c:310:23: warning: implicit declaration of function ‘MIN_OF’; did you mean ‘MIN’? [-Wimplicit-function-declarati
on]
  memcpy(tmp, hdr_arc, MIN_OF(strlen(hdr_arc), sizeof tmp - 1));
                       ^~~~~~
                       MIN
  CC       opendmarc-opendmarc-arcseal.o
opendmarc-arcseal.c: In function ‘opendmarc_arcseal_parse’:
opendmarc-arcseal.c:233:4: warning: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Wimplicit-function-decla
ration]
    strlcpy(as->algorithm, tag_value, sizeof as->algorithm);
    ^~~~~~~
    strncpy
  CC       opendmarc-opendmarc-dstring.o
  CC       opendmarc-parse.o
  CC       opendmarc-test.o
  CC       opendmarc-util.o
  CCLD     opendmarc
/usr/local/lib/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../x86_64-pc-linux-gnu/bin/ld: opendmarc-opendmarc-arcares.o: in function `o
pendmarc_arcares_arc_parse':
/git/opendmarc-github/opendmarc/opendmarc-arcares.c:310: undefined reference to `MIN_OF'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:528: opendmarc] Error 1
make[3]: Leaving directory '/git/opendmarc-github/opendmarc'
make[2]: *** [Makefile:838: all-recursive] Error 1
make[2]: Leaving directory '/git/opendmarc-github/opendmarc'
make[1]: *** [Makefile:484: all-recursive] Error 1
make[1]: Leaving directory '/git/opendmarc-github'
make: *** [Makefile:395: all] Error 2
```
fix:
```diff
--- a/opendmarc/opendmarc-arcares.c
+++ b/opendmarc/opendmarc-arcares.c
@@ -21,6 +21,11 @@
 # include <bsd/string.h>
 #endif /* USE_BSD_H */
 
+/* libstrl if needed */
+#ifdef USE_STRL_H
+# include <strl.h>
+#endif /* USE_STRL_H */
+
 #include "opendmarc-arcares.h"
 
 #define OPENDMARC_ARCARES_MAX_FIELD_NAME_LEN 255
@@ -307,7 +312,7 @@ opendmarc_arcares_arc_parse (u_char *hdr_arc, struct arcares_arc_field *arc)
        memset(arc, '\0', sizeof *arc);
        memset(tmp, '\0', sizeof tmp);
 
-       memcpy(tmp, hdr_arc, MIN_OF(strlen(hdr_arc), sizeof tmp - 1));
+       memcpy(tmp, hdr_arc, MIN(strlen(hdr_arc), sizeof tmp - 1));
 
        while ((token = strsep((char **)&tmp_ptr, " ;")) != NULL)
        {
diff --git a/opendmarc/opendmarc-arcseal.c b/opendmarc/opendmarc-arcseal.c
--- a/opendmarc/opendmarc-arcseal.c
+++ b/opendmarc/opendmarc-arcseal.c
@@ -22,6 +22,11 @@
 
 #include "opendmarc-arcseal.h"
 
+/* libstrl if needed */
+#ifdef USE_STRL_H
+# include <strl.h>
+#endif /* USE_STRL_H */
+
 #define OPENDMARC_ARCSEAL_MAX_FIELD_NAME_LEN 255
 #define OPENDMARC_ARCSEAL_MAX_TOKEN_LEN      512
 
```
Besides, there are `MAX_OF` and `MIN_OF` in `opendmarc/opendmarc-arcseal.c`.

Tables arcauthresults and arcseal are not mentioned in db/README.schema.

**Comment by jikamens** [comment]
Just stumbled across this. Confused about how a simple bug with a simple fix that was reported almost four months ago still isn't patched in the source tree. Is anybody maintaining this project?

**Comment by hdatma** [comment]
This issue was opened in 2018. Today, August 2020, the pathced file (opendmarc/opendmarc-arcares.c) no longer exists. Can you close this issue?

**Comment by dilyanpalauzov** [comment]
The patched file does exist on the develop branch.

**Comment by hdatma** [comment]
> cd /tmp/opendmarc-1.3.3/                                                                                                                                                                                                                                                               
find . -name opendmarc-arcares.c
[empty]

> cd ..
> git clone https://github.com/trusteddomainproject/OpenDMARC.git
Cloning into 'OpenDMARC'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 5375 (delta 32), reused 31 (delta 12), pack-reused 5306
Receiving objects: 100% (5375/5375), 1.79 MiB | 1.49 MiB/s, done.
Resolving deltas: 100% (3904/3904), done.

> cd OpenDMARC/                                                                                                                                                                                                                                                                         
find . -name opendmarc-arcares.c

**Comment by dilyanpalauzov** [comment]
The development of OpenDMARC is done on a branch called `develop`.  The change to this branch has to be done explicitly after `git clone`.  That branch has the file  opendmarc-arcares.c .
