### ISSUE TITLE
Doubled section HoldQuarantinedMessages in opendmarc/opendmarc.conf.sample

### ISSUE THREAD

**Issue by rapsys** [trusteddomainproject/OpenDMARC#244]
Hi,

It seems the section HoldQuarantinedMessages is duplicated in configuration sample.

One is above and one after IgnoreAuthenticatedClients section.

Best regards

**Comment by glts** [comment]
Duplicate of #165

**Comment by rapsys** [comment]
Sorry, I missed it and will close this duplicate.
