### ISSUE TITLE
snprintf in opendmarc.c uses wrong buffer size

### ISSUE THREAD

**Issue by jikamens** [trusteddomainproject/OpenDMARC#28]
The `snprintf` into `arcseal_buf` in `mlfi_oem` in `opendmarc.c` uses `sizeof arcseal_str` when it should use `sizeof arcseal_buf`. This causes a crash on my system:

```
(gdb) where
#0  0x00007f764bd04277 in raise () from /lib64/libc.so.6
#1  0x00007f764bd05968 in abort () from /lib64/libc.so.6
#2  0x00007f764bd46d37 in __libc_message () from /lib64/libc.so.6
#3  0x00007f764bde66e7 in __fortify_fail () from /lib64/libc.so.6
#4  0x00007f764bde4862 in __chk_fail () from /lib64/libc.so.6
#5  0x00007f764bde3f7b in __vsnprintf_chk () from /lib64/libc.so.6
#6  0x00007f764bde3e98 in __snprintf_chk () from /lib64/libc.so.6
#7  0x0000000000408efb in snprintf (__fmt=0x40f678 "%s{ \"i\": %d, \"d\":\"%s\", \"s\":\"%s\", \"ip\":\"%s\" }", __n=2049, __s=0x7f7649099020 "") at /usr/include/bits/stdio2.h:64
#8  mlfi_eom (ctx=0x202ed70) at opendmarc.c:3536
```

**Comment by thegushi** [comment]
jikamens,

This is on our develop branch, credited to you, so it looks like we pulled it in at some point.

Are you able to pull down our "develop" branch and test with it?

-Dan Mahoney

**Comment by thegushi** [comment]
Actually, it looks as though this made it into 1.4.0 already.  I'm going to close this out.  If you're still seeing the same issue, please reopen.
