### ISSUE TITLE
opendmarc milter needs shorter DNS lookup timeouts (?) to avoid freaking out sendmail

### ISSUE THREAD

**Issue by jikamens** [trusteddomainproject/OpenDMARC#30]
Recent spam I received:

```
Sep 23 08:01:10 myhostname sendmail[20145]: w8NC160P020145: from=<parroquia.sanlucas@ceaba.org.ar>, size=2051, class=0, nrcpts=1, msgid=<44A678C4-C767-4A1B-A552-6473DE9C42EF@mail138.cylarcom.net>, proto=ESMTP, daemon=MTA, relay=mail138.cylarcom.net [201.216.208.138]
Sep 23 08:01:11 myhostname sendmail[20145]: w8NC160P020145: Milter add: header: X-Bogosity: Spam, tests=bogofilter, spamicity=1.000000, version=1.2.3, milter_id=4eb2.5ba78087.702db8f
Sep 23 08:01:11 myhostname mimedefang.pl[23745]: w8NC160P020145: MDLOG,w8NC160P020145,mail_in,,,<parroquia.sanlucas@ceaba.org.ar>,<jik@my-email-domain>,Low interest rate loans
Sep 23 08:01:11 myhostname sendmail[20145]: w8NC160P020145: Milter add: header: X-Scanned-By: MIMEDefang 2.84
Sep 23 08:01:11 myhostname opendkim[977]: w8NC160P020145: mail138.cylarcom.net [201.216.208.138] not internal
Sep 23 08:01:11 myhostname opendkim[977]: w8NC160P020145: not authenticated
Sep 23 08:01:11 myhostname opendkim[977]: w8NC160P020145: no signing domain match for 'ceaba.org.ar'
Sep 23 08:01:11 myhostname opendkim[977]: w8NC160P020145: no signing subdomain match for 'ceaba.org.ar'
Sep 23 08:01:11 myhostname opendkim[977]: w8NC160P020145: no signature data
Sep 23 08:01:11 myhostname sendmail[20145]: w8NC160P020145: Milter insert (1): header: DKIM-Filter:  OpenDKIM Filter v2.11.0 myhostname.kamens.us w8NC160P020145
Sep 23 08:01:21 myhostname sendmail[20145]: w8NC160P020145: Milter (opendmarc): timeout before data read, where=eom
Sep 23 08:01:21 myhostname sendmail[20145]: w8NC160P020145: Milter (opendmarc): to error state
Sep 23 08:01:21 myhostname sendmail[20236]: w8NC160P020145: to=<jik@my-email-domain>, delay=00:00:11, xdelay=00:00:00, mailer=local, pri=32540, dsn=2.0.0, stat=Sent
Sep 23 08:01:24 myhostname opendmarc[24511]: w8NC160P020145: SPF(mailfrom): parroquia.sanlucas@ceaba.org.ar pass
Sep 23 08:01:25 myhostname opendmarc[24511]: w8NC160P020145: ceaba.org.ar none
Sep 23 08:01:25 myhostname opendmarc[24511]: w8NC160P020145: Authentication-Results header add failed
Sep 23 08:01:25 myhostname opendmarc[24511]: w8NC160P020145: DMARC-Filter header add failed
```

I'm assuming that what's going on there in that 10-second gap is opendmarc waiting for a response to a DNS query, though I suppose that could be a bad guess. If I'm right, then I think you need to reduce the timeouts on those query so that opendmarc can finish its work within the time sendmail is expecting.

**Comment by jikamens** [comment]
I should mention that this isn't a one-off, I see it happen about once per day on my (small) mail server.

**Comment by dilyanpalauzov** [comment]
All this haplens within 15 seconds, according to the logs.  The README says the default timeout for sendmail is ten seconds.  You can’t make sendmail faster, but you can make sendmail more patient, by asking it to wait longer.  Check documentation on configuring milters.  Finally, if opendmarc gives up earlier, should it temporary reject the mail, as the failire is of transient nature, or what?

**Comment by jikamens** [comment]
Making sendmail wait longer is not the correct fix. Any DNS lookup that takes more than a few seconds almost certainly isn't ever going to return anything non matter how long you wait. As I said, the correct fix is for opendmarc to use a shorter DNS timeout. And as for the question of how it should handle the timeout, I assume that question is already answered because there is already code in opendmarc to deal with DNS lookup failures.

**Comment by mskucherawy** [comment]
OpenDMARC uses res_query() or res_nquery() out of the box, which don't have direct timeout control (that I know of).

OpenDKIM has support for libunbound, which could be imported to OpenDMARC to provide this control.

**Comment by jikamens** [comment]
I think you can change the timeout for `res_query` and `res_nquery` by setting the `RES_TIMEOUT` environment variable early in your program, before any resolver functions are called?

**Comment by martinbogo** [comment]
@jikamens OpenDMARC shouldn't be changing the system environment variables during runtime.  It's user-configurable before sendmail or postfix execute the milter.  This is a user configuration solution. 

@mskucherawy is correct, there is no direct way to control res_query() or res_nquery() out of the box.  

Once the next release of OpenDMARC is rolled out we'll look at perhaps moving it to libunbound or whatever is appropriate for the major downstream distributions that use the Trusted Domain Project tools, since OpenDKIM does already have support.

For now, I'm closing this issue.
