### ISSUE TITLE
milter crashes on invalid ARC-Authentication-Results header

### ISSUE THREAD

**Issue by jikamens** [trusteddomainproject/OpenDMARC#31]
This ARC-Authentication-Results header causes OpenDMARC to crash:

```
ARC-Authentication-Results:i=1; mrouter01.cs.umd.edu; dkim=pass (1024-bit rsa key sha256)
  header.d=cs.umd.edu header.i=@cs.umd.edu header.b=wYOPRSsy header.a=rsa-sha256
  header.s=csmx; (null)=pass; (null)=pass (MX Record found) smtp.domain=cs.umd.edu
  policy.org_domain=umd.edu policy.is_org=no; arc=none smtp.client-ip=128.8.128.201
```

The header is invalid because two of the methods listed in it are `(null)`.

The crash occurs later after parsing, when `mlfi_oem` calls `opendmarc_ares_list_pluck` with a null `aar_hdr` because the one AAR header in the message couldn't be parsed, and that function asserts that `aar_hdr` is non-null and crashes.

An invalid header should not cause the milter to crash; it should, instead, behave as if the ARC seal is not there at all, or as if it comes from an untrusted domain, or as if it's not there at all. Any of these would be preferable to crashing.

**Comment by martinbogo** [comment]
I have validated this bug, it affects all current builds of OpenDMARC and needs to be fixed. Added ot the triage list.
