### ISSUE TITLE
Issues not imported from sourceforge

### ISSUE THREAD

**Issue by kitterma** [trusteddomainproject/OpenDMARC#34]
There are a large number of open tickets, many with good patches on sourceforge that should be brought over.

**Comment by martinbogo** [comment]
We are aware of the issues in Sourceforge and will be creating new PR's and issues based on any new input from downstream contributors.

**Comment by kitterma** [comment]
Let me make sure I understand:

The resolution of this ticket is "We know, we don't care"?

**Comment by martinbogo** [comment]
Scott,

Nope!

It's "We have switched platforms."

A lot of the issues and tickets on SF are quite old, and as the new
maintainer I'm going to look through them and create new issues here on
GitHub.

**Comment by kitterma** [comment]
Thanks for the clarification.
