### ISSUE TITLE
Yahoo! feedback loop/ARF reports arrive without Date: header, so tolerate them with RequiredHeaders: 1

### ISSUE THREAD

**Issue by dilyanpalauzov** [trusteddomainproject/OpenDMARC#37]
```diff
diff --git a/opendmarc/opendmarc.c b/opendmarc/opendmarc.c
--- a/opendmarc/opendmarc.c
+++ b/opendmarc/opendmarc.c
@@ -2324,7 +2324,8 @@ mlfi_eom(SMFICTX *ctx)
            dmarcf_findheader(dfc, "From", 1) != NULL)
                reqhdrs_error = "not exactly one From field";
 
-       if (dmarcf_findheader(dfc, "Date", 0) == NULL ||
+       if ((dmarcf_findheader(dfc, "Date", 0) == NULL
+            && strcmp(from->hdr_value, "Yahoo! Mail AntiSpam Feedback <feedback@arf.mail.yahoo.com>") != 0)||
            dmarcf_findheader(dfc, "Date", 1) != NULL)
                reqhdrs_error = "not exactly one Date field";
 

```
Needless to say I prefer if this is fixed on sender’s side, but I have no influence on Yahoo!  I want to have `RequireHeaders: on` in order to get less spam, but I also want to receive the mails from Yahoo FBL to remove subscribers from mailing lists.

**Comment by mskucherawy** [comment]
We will push to get this fixed on the sender side.  Fixing it here, especially with a specific string that the sender could change at any time, just doesn't make sense.

**Comment by dilyanpalauzov** [comment]
Unfortunately I have not managed to arrange fixing on the sender side, hence the changeset.

**Comment by martinbogo** [comment]
Changing something in code to adjust for a sender ( even one as large as Yahoo ) isn't the right way to go.  The sender is using a broken implementation and I agree with @mskucherawy that fixing it here doesn't make sense.  

Closing this issue.

**Comment by dilyanpalauzov** [comment]
Fixing opendkim (and opendmarc) to work right, has been the longest taking challenge I ever had in my life, considering that the aggregate reports say, that something is not working, but do not say what is not working.

To the extend that OpenDMARC offers options that prevent the receivers to receive emails, which the receivers want to receive (here ARF messages from Yahoo without Date header), then at least the documentation shall reference this.  This shall be documented somewhere.
