### ISSUE TITLE
DMARC not failing subdomains

### ISSUE THREAD

**Issue by reticentnz** [trusteddomainproject/OpenDMARC#43]
I recently implemented OpenDMARC on Debian8 (Jessie) and have observed an issue with "RejectFailures true" and subdomains. I have a policy on a test domain (test.com) I'm playing with:

v=DMARC1; p=none; sp=reject; rua=mailto:test@rep.dmarcanalyzer.com; ruf=mailto:test@rep.dmarcanalyzer.com; pct=100; fo=1

What's important is that I have sp set to reject, ie reject on subdomains. What I'm seeing is if I send an email from bob@test.com it works OK (this is what I would expect as p=none) however when I send an email from bob@test.test.com it also works. Under this situation shouldn't it fail? 

When forwarding to Gmail I see the correct behaviour, bob@test.com is accepted, but bob@test.test.com isn't. 

Any ideas?

**Comment by dilyanpalauzov** [comment]
I cannot confirm this problem.  I also use sp=reject; p=none and emails from subdomain.x.tld are rejected by OpenDMARC.  As a rule of thumb, use OpenDMARC from the develop branch.

Are you sure that the email is coming from outside and passed OpenDMARC (rather than an email within your serve, which does not reach OpenDMARC).

**Comment by iredmail** [comment]
If no any commit in 2 years and still bugs found and reported in issue tracker, I considered it as dead or abandoned. :(

I recently experienced an issue that SPF check passed but opendmarc still rejected it...

**Comment by AntiFreeze** [comment]
@reticentnz what's in your SPF record? could you dump the headers of the message upon receipt?

**Comment by martinbogo** [comment]
I also cannot confirm or replicate this issue.  If someone else sees this issue, please document:

- The SPF record
- appropriate log entries ( sanitized )
- debug output ( sanitized ) 

Closing the issue.  May re-open if there's more information.
