### ISSUE TITLE
opendmarc_util_finddomain may parse From: incorrectly

### ISSUE THREAD

**Issue by scandox** [trusteddomainproject/OpenDMARC#44]
I encountered an unusual From address in production (modified here for privacy reasons):

    From: "\"AcmeCorp, Inc.\"" <ordersender-prod@otheraddress.random.com>

The function `opendmarc_util_finddomain` will return simply "AcmeCorp" from this address. The escaping shown is part of the From address the sender generated.

The net result for these emails was that the pdomain was set to "AcmeCorp" but it ultimately returned a failed DMARC check as follows:

    Authentication-Results: mail1.tstechnology.net; dmarc=fail (p=reject dis=none) header.from=otheraddress.random.com

In the report the results were something like:
```

job 9124B80D79
reporter mail1.mailprovider.com
received 1561649315
ipaddr x.x.x.x
from otheraddress.random.com
mfrom otheraddress.random.com
dkim otheraddress.random.com 0
spf 0
pdomain AcmeCorp
policy 16
rua mailto:postmaster@otheraddress.random.com
pct 100
adkim 114
aspf 114
p 114
sp 110
align_dkim 5
align_spf 5
action 2
```
Not entirely sure whose responsibility this is. I guess the From is malformed, but then if the From is malformed shouldn't opendmarc ignore it?

**Comment by martinbogo** [comment]
If the From: field is malformed, this is largely the responsibility of the MTA  rules to deal with.  

This is more akin to "Garbage in / Garbage out" and it's not the responsibility of the OpenDMARC milter.
