### ISSUE TITLE
Incorrect rejection even sender server is listed in SPF

### ISSUE THREAD

**Issue by iredmail** [trusteddomainproject/OpenDMARC#50]
Dear developers,

We experienced few incorrect rejections by OpenDMARC-1.3.2, even sender server IP address is explicitly listed in SPF. Here's the latest one (on Debian 10):

Postfix log:

```
Sep 11 09:46:05 mail postfix/cleanup[319]: 46Sv8s1Vd4z1x2H: milter-reject:
  END-OF-MESSAGE from mta202a-ord.mtasv.net[104.245.209.202]: 5.7.1
  rejected by DMARC policy for bitpanda.com; from=<pm_bounces@pm.mtasv.net>
  to=<user@mydomain.com> proto=ESMTP helo=<mta202a-ord.mtasv.net>
```

DNS records of the `bitpanda.com` mentioned in Postfix log:

```
v=spf1 mx include:_spf.mlsend.com include:spf.mtasv.net include:_spf.google.com include:amazonses.com ~all
```

DNS records of sender domain "pm.mtasv.net":

```
v=spf1 include:spf.mtasv.net ~all
v=DMARC1; p=none; pct=100; rua=mailto:<email>,mailto:<email>; sp=none; aspf=r;
```

SPF of `spf.mtasv.net`:

```
v=spf1 ip4:50.31.156.96/27 ip4:104.245.209.192/26 ip4:50.31.205.0/24 ip4:147.160.158.0/24 ~all
```

Sender server IP `104.245.209.202` is in network `104.245.209.192/26` (spf of `spf.mtasv.net`).

According to its DMARC record `aspf=r`, this email should be passed. But it's actually rejected.

Client disabled OpenDMARC and received further emails from same sender and sender server, it's normal business emails like he received before (from same sender and sender server).

This is just one of the few similar incorrect rejections. As a temporarily solution, we have to ask clients to disable OpenDMARC until it's fixed by upstream and updated by Linux vendors via yum/apt repo.

**Comment by L1ghtn1ng** [comment]
@iredmail you are better of finding a replacement for this with something else that is better maintained as I have no clue if this is as master if from 2017. iRedmail needs to have a form of dkim in it, this would be a good alternative and it has ML which is a really neat feature https://www.rspamd.com/doc/quickstart.html#the-rspamadm-command

**Comment by L1ghtn1ng** [comment]
also the docs for rspamd are good

**Comment by L1ghtn1ng** [comment]
You will want to use https://www.rspamd.com/announce/2019/10/28/rspamd-2.1.html this version as there was an issue with dkim in 2.0 which is fixed in 2.1

**Comment by L1ghtn1ng** [comment]
@iredmail you would need to add the ppa as this package is not installable by default https://www.rspamd.com/downloads.html

**Comment by L1ghtn1ng** [comment]
@iredmail https://www.rspamd.com/comparison.html

**Comment by L1ghtn1ng** [comment]
@iredmail can do a lot of things this can and can replace a lot of things in iredmail with just this, very powerful and would be a awesome addition to iredmail

**Comment by L1ghtn1ng** [comment]
@iredmail recommend going through the modules https://www.rspamd.com/doc/modules/dmarc.html https://www.rspamd.com/doc/modules/

**Comment by jikamens** [comment]
@L1ghtn1ng the aggressive proselytizing you are doing in an OpenDMARC issue about an entirely different software package is highly inappropriate. Even your first comment was slightly out-of-line, although it could perhaps be forgiven as an honest desire to help. But going on and on and on after that is just entirely over the line. Please cut it out.

**Comment by L1ghtn1ng** [comment]
Sorry, did not mean to offend anyone and was just providing more information, again my sincere apologies
________________________________

**Comment by Neustradamus** [comment]
@AntiFreeze, @mskucherawy: Any news about this bug?
It can be solved?

**Comment by martinbogo** [comment]
I am currently triaging and going through the backlog of reported issues and pull requests in order from newest to oldest.   I am discussing with downstream linux distributions that have implemented patches, one of which may address this issue.  

Either way, this is being added to the triage list and will be addressed.

**Comment by iredmail** [comment]
Dear @martinbogo 

Any update?

**Comment by thegushi** [comment]
Hey there iredmail, quick question for you about this bug -- was opendmarc in this case compiled with libspf2 support or only using the built-in spf support?

-Dan

**Comment by iredmail** [comment]
It's the one offered in official Debian 10 apt repository, i didn't check the compile options. sorry.

**Comment by thegushi** [comment]
Hey there,

I'm marking this as part of the 1.4.1 milestone.  We'd greatly appreciate if you could compile and test manually (yes, I know you're currently dependent on the debian packages).  If you're not able to for various reasons, we can address this after 1.4.1. drops.

To be clear, this feels like a bug, not a new feature, and we're interested in getting it fixed soon.  We've done some SPF fixes in the new branch

-Dan

**Comment by iredmail** [comment]
Dear @thegushi 

I’m sorry that I don’t have environment for testing now. Could you help test it instead?

**Comment by mskucherawy** [comment]
I tested this against the "develop" branch which will soon yield the 1.4.1 release, and it appears to do the right thing.  If you're able to pull down the current source and test it locally, you might find it's working correctly.

**Comment by thegushi** [comment]
We believe this has been fixed and I'm closing it out.  When 1.4.1 drops if this issue persists, please feel free to reopen this issue.
