### ISSUE TITLE
Exclude non-free Internet Drafts from release tarball

### ISSUE THREAD

**Issue by glts** [trusteddomainproject/OpenDMARC#58]
In Debian, we cannot use the release tarball directly, because it
contains files that Debian considers non-free. We have to repack the
tarball, and use an additional `+dfsg` suffix in the package version,
which is not ideal.

List of files that are non-free and have to be excluded in Debian:

```
docs/draft-dmarc-base-00.txt
docs/draft-dmarc-base-01.txt
docs/draft-dmarc-base-02.txt
docs/draft-dmarc-base-03.txt
docs/draft-dmarc-base-04.txt
docs/draft-dmarc-base-05.txt
docs/draft-dmarc-base-06.txt
docs/draft-dmarc-base-07.txt
docs/draft-dmarc-base-08.txt
docs/draft-dmarc-base-09.txt
docs/draft-dmarc-base-10.txt
docs/draft-dmarc-base-11.txt
docs/draft-dmarc-base-12.txt
docs/draft-dmarc-base-13.txt
```

Please consider whether it is possible to drop these files from the
release tarball. It would make maintenance of the package in Debian a
little bit easier.

**Comment by martinbogo** [comment]
Why are these considered non-free?  The Author of OpenDMARC ( Murray ) is the author and copyright holder of the document.  As he is the original author, he holds the moral rights of the work ( worldwide ) and the copyright ( USA ).

To the best of my knowledge, the work was not produced under contract and should have no further encumbrances as it both has one Author, and that Author has placed it as part of the OpenDMARC documentation base with no further restrictions or stipulations.

@mskucheraway, do you have any opinion or further comment on this?

**Comment by mskucherawy** [comment]
All of these files were added for convenient reference as DMARC was under development.  When it became an RFC, these all became obsolete.  We can just delete them.

**Comment by martinbogo** [comment]
Okay, deleting them -- removed the directory and reference to it from the Makefile.am

**Comment by martinbogo** [comment]
PR #60 created.  Will use it to create a 1.4.0-Beta2 release directly to master.  Since it's documentation-only we won't have to test a rollup in the development branch.

**Comment by glts** [comment]
Thank you!

**Comment by kitterma** [comment]
Thanks.  For future reference they are considered non-free because they have restrictions on modification. See [DFSG point 3](https://www.debian.org/social_contract#guidelines).  This applies to virtually all RFCs.

**Comment by glts** [comment]
@mskucherawy @martinbogo I’m afraid something is wrong with the release tarball.

Many changes present in 1.4.0-Beta1 are missing/have been reverted. The entire section on version 1.4.0 in the RELEASE NOTES document is deleted.

Could it be that you released 1.4.0-Beta2 on top of 1.3.2, instead of 1.4.0-Beta1?

**Comment by martinbogo** [comment]
https://github.com/trusteddomainproject/OpenDMARC/compare/rel-opendmarc-1-4-0-Beta1...rel-opendmarc-1-4-0-Beta2

When comparing the releases, the only changes between the Beta1 and Beta2
are that the docs directory was removed, and the Makefile updated.

I'll download and check the tarballs, to see if there might have been an
issue when GitHub made them

**Comment by martinbogo** [comment]
Yep!  Since this is a master release, this is rel-opendmarc-1-3-3 -- fixed
the tag and committed correctly.

Rolled back 1.4.0-Beta2 --- we're actually going to try for a roll-up
release, with the major number adjusted to account for the long gap in
releases.  ( likely 1.5.0 with a couple quick shakedown Betas )
