### ISSUE TITLE
Question about merge "Fix res_ninit() detection with glibc"  issue to master

### ISSUE THREAD

**Issue by jekin000** [trusteddomainproject/OpenDMARC#61]
hi  
I found there is fixed issue about res_ninit(), and it has already been merged to develop branch. 
https://github.com/trusteddomainproject/OpenDMARC/pull/2
But in master branch, it seems no related code,  is there any concern about the fix?

**Comment by martinbogo** [comment]
We will be rolling all the patches in the develop branch into the new
release.

-Martin

**Comment by thegushi** [comment]
This is present in 1.4.0, this can be closed.

**Comment by martinbogo** [comment]
Merged, closed
