### ISSUE TITLE
Incorrect domain parsing for policy verification when header contain quoted-string

### ISSUE THREAD

**Issue by netaso** [trusteddomainproject/OpenDMARC#72]
Hi,

We have seen several incorrect DMARC failures in OpenDMARC-1.3.2, when SPF check and alignment were passing.
After investigating the issue, we have identified that all failures have the same "From:" header pattern, which contain a comma inside quoted-string that were inside quoted string. 
For example, below header resulted with `pdomain=Medtronic`:
`From: "\"Medtronic, Inc.\"" <ordersender-prod@ansmtp.ariba.com>`

When it should be `pdomain=ansmtp.ariba.com`.
This invalid parsing has caused SPF alignment to fail, thus the message was rejected.

According to RFC5322 3.2.4:

> _Also note that since quoted-pair is allowed in a quoted-string, the quote and backslash characters may appear in a quoted-string so long as they appear as a quoted-pair._

Regards,
Neta

**Comment by thegushi** [comment]
Are you still seeing this issue with 1.4.0?

-Dan

**Comment by mskucherawy** [comment]
The fix to Issue #104 which just landed probably fixes this as well.  The parsing of quotes was broken.

**Comment by thegushi** [comment]
Hey there.  I'm assigning the 1.4.1 Milestone to this.  We would strongly recommend building our "develop" branch and seeing if the issue evidences with that.  If we do a prerelease or a beta for 1.4.1, we'll also ask for testing there.

**Comment by thegushi** [comment]
We believe this has been fixed and I'm closing it out.  When 1.4.1 drops if this issue persists, please feel free to reopen this issue.
