### ISSUE TITLE
SIGSEGV in opendmarc_policy_parse_dmarc()

### ISSUE THREAD

**Issue by MASHtm** [trusteddomainproject/OpenDMARC#78]
opendmarc_policy.c:1060ff reads for 1.3.2 and master:
```
			xp = opendmarc_util_cleanup(xp, xbuf, sizeof xbuf);
			if (xp != NULL || strlen((char *)xp) > 0)
				{
```
I'm pretty sure there should be a '&&' instead of '||' to prevent NULL dereference.

At least this causes coredumps here for:
```
# host -t txt _dmarc.varo-inform.com
_dmarc.varo-inform.com descriptive text "v=DMARC1\; p=reject\; sp=reject\; rf=mailto:postmaster@varo-inform.com\; pct=100\; ri=86400"
```

**Comment by glts** [comment]
> I'm pretty sure there should be a '&&' instead of '||' to prevent NULL dereference.

Yes, see also #56 (fix for the same mistake).

**Comment by martinbogo** [comment]
Merged, fixed, closed.
