### ISSUE TITLE
tests fail because bcx.com no longer exists

### ISSUE THREAD

**Issue by hdatma** [trusteddomainproject/OpenDMARC#92]
```
=======================================================
   OpenDMARC 1.3.2: libopendmarc/tests/test-suite.log
========================================================

# TOTAL: 8
# PASS:  7
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_spf
==============

Test opendmarc_spf_ip6_tests(): 5 pass, 0 fail
Test opendmarc_spf_ip4_tests(): 2 pass, 0 fail
Error: ip="204.14.152.228", mfrom="<foo@bcx.com>", helo="bcx.com", spf="v=spf1 ip4:204.14.152.228 -all", error(2)= Hard Fail: Reject
Error: ip="204.14.152.228", mfrom="<foo@bcx.com>", helo="bcx.com", spf="v=spf1 mx  -all", error(2)= Hard Fail: Reject
Error: ip="204.14.152.228", mfrom="<foo@bcx.com>", helo="bcx.com", spf="NULL", error(3)= Host name lookup failure
Error: ip="204.14.152.228", mfrom="<>", helo="bcx.com", spf="v=spf1 mx  -all", error(2)= Hard Fail: Reject
Error: ip="204.14.152.228", mfrom="MAILER_DAEMON", helo="bcx.com", spf="v=spf1 mx  -all", error(2)= Hard Fail: Reject
Error: ip="174.137.46.2", mfrom="<foo@bcx.com>", helo="bcx.com", spf="v=spf1 include:_netblocks.zdsys.com  -all", error(2)= Hard Fail: Reject
Error: ip="204.14.152.228", mfrom="<foo@sf1.bcx.com>", helo="sf1.bcx.com", spf="v=spf1 include:bcx.com       -all", error(2)= 'INCLUDE' Domain Lookup Failed
Error: ip="204.14.152.228", mfrom="<foo@bcx.com>", helo="bcx.com", spf="v=spf1 -a", error(2)= Required 'A' bu no 'A' records with -a specified
Error: ip="204.14.152.228", mfrom="<foo@bcx.com>", helo="bcx.com", spf="v=spf1  a -all", error(2)= Required 'A' lookup failed to find 'A' records
Error: ip="204.14.152.228", mfrom="<foo@bcx.com>", helo="bcx.com", spf="v=spf1 a:sf1.bcx.com -all", error(2)= Required 'A' lookup failed to find 'A' records
Error: ip="204.14.152.228", mfrom="<foo@bcx.com>", helo="bcx.com", spf="v=spf1 ptr -all", error(2)= Hard Fail: Reject
Error: ip="204.14.152.228", mfrom="<foo@bcx.com>", helo="bcx.com", spf="v=spf1 ptr:bcx.com -all", error(2)= Hard Fail: Reject
Error: ip="204.14.152.228", mfrom="<foo@bcx.com>", helo="bcx.com", spf="v=spf1 exists:%{s} -all", error(2)= Hard Fail: Reject
Error: ip="204.14.152.228", mfrom="<foo@sf1.bcx.com>", helo="sf1.bcx.com", spf="v=spf1 redirect:bcx.com       -all", error(2)= 'REDIRECT' Syntax Error
Test opendmarc_spf_test_records(): 8 pass, 14 fail
```

```
>unbound-host -rvD bcx.com                                                                                                                                           
bcx.com has no address (insecure)
bcx.com has no IPv6 address (insecure)
bcx.com has no mail handler record (insecure)
```

**Comment by thegushi** [comment]
I poked murray in IM today and asked what the history of bcx.com is.  While using gmail is one option, we could also just put this stuff in trusteddomain.org.

**Comment by thegushi** [comment]
The bcx.com tests work for me under the current "Develop" branch.

This feels more like an SPF library test than a DNS test for me -- if I'm reading this right (I could be wrong) those tests are simlulated DNS lookups and I don't think they go out over the wire.  (Effectively they say "tell libspf you got this result, with this mfrom, this record, and this helo, and let it resolve it).

Now, the *live* tests that actually feed the milter, those do have the milter itself do DNS queries.  But that's not what's failing.

**Comment by hdatma** [comment]
> The bcx.com tests work for me under the current "Develop" branch.

They should fail, because the domain bcx.com does not exist.

> This feels more like an SPF library test than a DNS test for me -- if I'm reading this right (I could be wrong) those tests are simlulated DNS lookups and I don't think they go out over the wire. (Effectively they say "tell libspf you got this result, with this mfrom, this record, and this helo, and let it resolve it).

The SPF test needs answers from the DNS. Since bcx.com is dead, no DNS answers, and thus all SPF tests fail.  So, first we need a replacement for bcx.com (trusteddomain.org is ideal), then make sure it responds to TXT queries for SPF, then we can check the SPF tests by opendmarc.

> Now, the _live_ tests that actually feed the milter, those do have the milter itself do DNS queries. But that's not what's failing.

Let's get back to this once you have the first two points ironed out.

**Comment by thegushi** [comment]
The latest "develop" branch has gushi.org and isc.org in it in place of bcx.com, and all tests as written currently pass on my OpenBSD VM, using libspf2.  At some point we should set up a more formal testing domain, but Murray also has suggested that including a mock resolver might be useful.  As far as getting a working very-much-point release out the door, this will do.

-Dan
