### ISSUE TITLE
autoconf 2.70 - configure.ac has obselete macros 

### ISSUE THREAD

**Issue by gene-git** [trusteddomainproject/OpenDMARC#95]
autoconf 2.70 was released on December 8th and brings quite a few changes, some are not backward compatible. The r
elease note is here: 

https://lwn.net/Articles/839395/ 

configure.ac needs to be updated. 

There are now warnings during build: 
configure.ac:67: warning: The macro `AC_PROG_CC_C99' is obsolete. 
configure.ac:69: warning: The macro `AC_PROG_LIBTOOL' is obsolete. 
configure.ac:74: warning: The macro `AC_HELP_STRING' is obsolete. 
configure.ac:81: warning: The macro `AC_LANG_C' is obsolete. 
configure.ac:81: warning: The macro `AC_TRY_LINK' is obsolete. 
configure.ac:84: warning: The macro `AC_HEADER_STDC' is obsolete. 
configure.ac:85: warning: The macro `AC_HEADER_TIME' is obsolete. 
configure.ac:498: warning: AC_OUTPUT should be used without arguments.

**Comment by thegushi** [comment]
Gene,

The action here is just to figure out how *old* an Autoconf we can handle, and make sure that we don't break that.  Autoconf 2.70 isn't widely packaged everywhere and we'd like to stay compatible with what's out there.

**Comment by thegushi** [comment]
Which OS are you on?  (Dist and version?)

Also, on Arch Linux at least, our build is pretty broken.  This is going to be a somewhat major overhaul of our autoconf setup, and will likely want to wait until after 1.4.1 (which is what we're pushing the current patches into).

That said, it might be worthwhile surveying when the major distros (ubuntu, freebsd, centos, openbsd) are likely to go to 2.70.

**Comment by gene-git** [comment]
Im on Arch. Nice to see some life/interest in these vital tools. Add fedora to the list as well to find out current tooling.
Fedora has autoconf 2.71 for Fedora 35[1].

Mine are:
```
autoconf 2.71
automake 1.16.3
binutils 2.36.1
gcc 10.2.0
```
`
[1] https://fedoraproject.org/wiki/Changes/Autoconf_271`

**Comment by thegushi** [comment]
Hey Gene,

I'm happy to say that I've built a version of configure.ac that has all the correct macros (as well as a fix for res_ninit), and it's awaiting someone to pull it in from thegushi/OpenDMARC to the "testing" branch

Once that happens, we will need people on several platforms to test this out.  Stay tuned.

**Comment by thegushi** [comment]
I just merged it into the testing branch.  Please give it a whirl and report back.  Note that this branch will be fairly stable, until it isn't.

In a perfect world we'd have created a testing_autoconf branch for this, but this is where we're at.

We're looking for: no errors, minimial warnings, cleaner compiles.  We'll test this on several of our own platforms.

**Comment by thegushi** [comment]
Hey there again Gene.  I just committed another patch to solve the BSD issues.  Apparently an autoconf macro needed to be declared twice, as it was being reset at some point in the process.

Please make sure your build still works and does not emit warnings.  Anyone else reading this, give things a whirl on the latest linux/bsd/etc.  (We know OpenBSD is still at issue, but we have a solution for that).

**Comment by gene-git** [comment]
pulled and rebuilt with latest commit ( f3d304dd86da80 ) builds just fine for me.

**Comment by thegushi** [comment]
We're happy to add you to the release notes as reporter.  Please let me know how you should be credited, if at all.

**Comment by gene-git** [comment]
Thank you - not necessary, you guys do all the real work - but I'm happy to test and help where I can.  Great to see things moving in a good direction.

**Comment by thegushi** [comment]
Hey Gene,

Just to drop you a line to let you know that we're getting ready to drop a 1.4.1 -- Our autoconf changes are not yet in the "Develop" branch, but should be soon.  We'd appreciate, when that happens, if you could check out and build "Develop" to see if any issues arise.

**Comment by gene-git** [comment]
Thanks for the heads up - of course - be happy to build and test the develop branch once the changes get merged in.

**Comment by thegushi** [comment]
Just to let you know I'm assigning this the 1.4.1 milestone.  While a full rewrite of our autoconf stuff to reflect the current "state" of autoconf might be warranted, for 1.4.1 the goal is "it builds without throwing errors".  If we do a beta or an rc, this will block on you (and us for our own platforms) for that.

**Comment by gene-git** [comment]
Sounds good - at moment I'm building testing branch 3 times daily - just tag me when you want me to test and let me know which branch(es) you'd like me to run builds for.

thanks for working on this.

**Comment by thegushi** [comment]
Gene,

The "testing" branch has been now merged into "develop".  Can you give it one more run?  There may be final tweaks happening (and at some point a full-on rewrite from scratch, but that's not for a .0.1 release.)

**Comment by gene-git** [comment]
Just pulled and built - build is clean and (build) tests all pass fine. Thank you!
```

PASS: test_dmarc_fetch
PASS: test_finddomain
PASS: test_dmarc_parse
PASS: test_tld
PASS: test_alignment
PASS: test_parse_to_buf
PASS: test_xml_parse
============================================================================
Testsuite summary for OpenDMARC 1.4.0
============================================================================
# TOTAL: 7
```

**Comment by gene-git** [comment]
Forgot to say - build was up to commit fc5e7279d6bddec

**Comment by gene-git** [comment]
I have a bit of a problem im trying to understand.

Using build from 'testing' - I sent test mail from gmail account to the mail server - dkim, spf and dmarc pass.

Installed and started the develop build - and now spf and dkim pass but dmarc fails

Email from same gmail account to same user here - staring at the headers but so far I don't see it.
I will change back to 'testing' build and see if dmarc passes again.

no other changes other than which build of opendmarc.
am quite perplexed by this one.

In both cases the envelope from matches the from header and matches  the dkim d=gmail.com and both dkim and spf pass.

Wonder what I could possibly have done ...

**Comment by gene-git** [comment]
Putting back the testing build (commit 6973893) works fine again - same test - gmail to same user.

Is it me - or has something changed/gone awry with develop build?

**Comment by thegushi** [comment]
Paste the headers here, or you can email them to me (github~gushi~org)?

(Also, that should be in a different "issue", please to create one?)

**Comment by thegushi** [comment]
er github at gushi dot org

**Comment by gene-git** [comment]
will send via email shortly

**Comment by thegushi** [comment]
We've resolved this in 144, I'm reclosing this issue.

-Dan
