### ISSUE TITLE
schema.sql script error with MySQL 8.0.22

### ISSUE THREAD

**Issue by bkeevil** [trusteddomainproject/OpenDMARC#98]
Line 31 of schema.sql thereabouts

``` sql
CREATE TABLE IF NOT EXISTS requests (
	id INT NOT NULL AUTO_INCREMENT,
	domain INT NOT NULL,
	repuri VARCHAR(255) NOT NULL,
        adkim TINYINT NOT NULL,
        aspf TINYINT NOT NULL,
        policy TINYINT NOT NULL,
        spolicy TINYINT NOT NULL,
        pct TINYINT NOT NULL,
        locked TINYINT NOT NULL DEFAULT '0',
	firstseen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastsent TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',

	PRIMARY KEY(id),
	KEY(lastsent),
	UNIQUE KEY(domain)
);
```

Error Code: 1067. Invalid default value for 'lastsent'

From: https://dev.mysql.com/doc/refman/8.0/en/datetime.html

> The value inserted must not have a zero for the month part, the day part, or both parts. This is enforced beginning with MySQL 8.0.22, regardless of the server SQL mode setting.

What should the default value be instead?

This will execute and is the lowest acceptable date value: `lastsent TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00'`

**Comment by thegushi** [comment]
Hey there,

Thanks for taking the time to help make our software better.  We'd love to be able to give you credit in our release notes, if you like.  At this point I've merged your patch into our "develop" branch for likely inclusion into the upcoming 1.4.1.

Please let us know how we should credit you.  Common options are "anonymous", "username at github" "Real Name" or "Real Name (email@address)".  Preferably translated to ASCII if need be.

**Comment by thegushi** [comment]
not closing this yet, just need info about how to credit

**Comment by bkeevil** [comment]
I answered this question on the pull request page.

**Comment by neildarlow** [comment]
Hi,

This change breaks things for MariaDB. From the Limitations section of the TIMESTAMP documentation:

`Because the TIMESTAMP value is stored as Epoch Seconds, the timestamp value '1970-01-01 00:00:00' (UTC) is reserved since the second #0 is used to represent '0000-00-00 00:00:00'.`

So, for MariaDB, the value '1970-01-01 00:00:00' produces the Error 1067 (42000) ... Invalid default value for 'lastsent'

A solution acceptable to more MySQL variants is required.

**Comment by hb9eue** [comment]
I suggest to re-open the issue as the table is not being created with MariaDB:

```
MariaDB [opendmarc]> CREATE TABLE IF NOT EXISTS requests (
    -> id INT NOT NULL AUTO_INCREMENT,
    -> domain INT NOT NULL,
    -> repuri VARCHAR(255) NOT NULL DEFAULT '',
    -> adkim TINYINT NOT NULL DEFAULT '0',
    -> aspf TINYINT NOT NULL DEFAULT '0',
    -> policy TINYINT NOT NULL DEFAULT '0',
    -> spolicy TINYINT NOT NULL DEFAULT '0',
    -> pct TINYINT NOT NULL DEFAULT '0',
    -> locked TINYINT NOT NULL DEFAULT '0',
    -> firstseen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -> lastsent TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
    -> 
    -> PRIMARY KEY(id),
    -> KEY(lastsent),
    -> UNIQUE KEY(domain)
    -> );
ERROR 1067 (42000): Invalid default value for 'lastsent'
```
